# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: myAgentPool

variables:
  azureServiceConnectionId: 'myServiceConnection'
  webAppName: 'agilewebapp243371'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'msdocs_sample_app'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: 
      name: myAgentPool
      vmImage: $(vmImageName)
    steps:
    - script: |
        export PATH=$HOME/.local/bin:$PATH
        python3 -m venv ~/.myenv
        source ~/.myenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        python3 -m pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: 'Step - Install requirements.txt'
      
    - task: ArchiveFiles@2
      displayName: 'Step - Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Step - Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: 
      name: myAgentPool
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : '
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              appType: webApp
